spring:
  application:
    name: mim.enterprise
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: postgres
    password: sakib11
    driver-class-name: org.postgresql.Driver

#    live
#    url: jdbc:postgresql://103.23.31.75:5432/ierpdb
#    username: ierpuser
#    password: Infx_321
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update      # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # optional, makes SQL easier to read

# Note: Do NOT explicitly set spring.jpa.properties.hibernate.dialect
# Hibernate will automatically detect PostgreSQLDialect from the JDBC URL.


###################################################################
#spring:
#  datasource:
#    url: jdbc:h2:file:./data/core        # In-memory database (data resets on restart)
#    driver-class-name: org.h2.Driver
#    username: sa                   # default username
#    password:                      # no password by default
#
#  h2:
#    console:
#      enabled: true                # enables browser console
#      path: /h2-console            # console URL â†’ http://localhost:8080/h2-console
#
#  jpa:
#    hibernate:
#      ddl-auto: update             # auto create/update tables
#    show-sql: true                 # show SQL in console
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
###################################################################
server:
  port: 8080

# JWT Configuration
#jwt:
#  secret: 9d1fC72rAqX4ZpB7sUe6JvQ3wKx0YmTnLpGhRfEoVbC8NsZtMiDaWyJqHuRtGk2P
#  expiration: 86400000  # 24 hours
#
#  # CORS Configuration
#cors:
#  allowed-origins:http://localhost:3000